name: Apply Terraform changes
env:
    TF_VAR_token: ${{ secrets.TOKEN }}

on:
  workflow_dispatch:  
jobs:
  apply_terraform_changes:
    runs-on: ubuntu-latest
    permissions:
     contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install zip
        run: sudo apt-get -y install zip

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.11.3
          terraform_wrapper: false
          
      - name: Get artifact from previous run
        run: |
          ARTIFACT_URL=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.head_run_id }}/artifacts" | \
            jq -r '.artifacts[0].archive_download_url')

          curl -L -o artifact.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $ARTIFACT_URL

          unzip artifact.zip -d ./
          
      - name: Display artifact content
        run: |
          cat ./terraform.tfstate
          
      - name: Teraform init
        run: terraform init
          
      - name: Terraform apply
        continue-on-error: true
        run: |
          echo '```'>>$GITHUB_STEP_SUMMARY
          terraform apply -auto-approve -no-color -input=false >> $GITHUB_STEP_SUMMARY
          echo '```'>>$GITHUB_STEP_SUMMARY
      - name: Upload Terraform State to Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: terraform-state
          path: |
            terraform.tfstate
