name: Plan Terraform changes
env:
    TF_VAR_token: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:  
jobs:
  plan_terraform_changes:
    runs-on: ubuntu-latest
    permissions:
        security-events: write
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4
          terraform_wrapper: false
          
      - name: Teraform init
        run: terraform init
        
      - name: Terraform plan
        run: |
          terraform plan -out=plan.tfplan
          echo '```'>>$GITHUB_STEP_SUMMARY
          terraform show -no-color -compact-warnings plan.tfplan >> $GITHUB_STEP_SUMMARY
          echo '```'>>$GITHUB_STEP_SUMMARY
