name: Plan Terraform changes
env:
    TF_VAR_token: ${{ secrets.TOKEN }}

on:
  workflow_dispatch:  
jobs:
  hello-world:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install zip
        run: sudo apt-get -y install zip

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4
          terraform_wrapper: false
          
      - name: Teraform init
        run: terraform init
        
      - name: Terraform plan
        run: |
          terraform plan -out=plan.tfplan
          echo '```'>>$GITHUB_STEP_SUMMARY
          terraform show -no-color plan.tfplan >> $GITHUB_STEP_SUMMARY
          echo '```'>>$GITHUB_STEP_SUMMARY
