name: Plan Terraform changes
env:
    TF_VAR_token: ${{ secrets.TOKEN }}

on:
  workflow_dispatch:  
jobs:
  plan_terraform_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Decrypt Terraform state file
        continue-on-error: true
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
         chmod +x ./decrypt.sh
         ./decrypt.sh

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.11.3
          terraform_wrapper: false
          
      - name: Teraform init
        run: terraform init
        
      - name: Terraform plan
        run: |
          terraform plan -out=plan.tfplan
          echo '```'>>$GITHUB_STEP_SUMMARY
          terraform show -no-color -compact-warnings plan.tfplan >> $GITHUB_STEP_SUMMARY
          echo '```'>>$GITHUB_STEP_SUMMARY
